services:
    postgres:
        image: postgres
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
    django:
        depends_on:
            - postgres
        build: django
        command: python app/manage.py runserver 0.0.0.0:8000
        volumes:
            - ./django/app:/app
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '8000:8000'
